---
- name: Simple playbook using community.general to create a file in /root
  hosts: all
  become: true
  
  tasks:
    - name: Set timezone to Asia/Tokyo
      community.general.timezone:
        name: Asia/Tokyo

