---
- name: Copy a file from /root/abhi to /home
  hosts: all
  become: yes
  tasks:
    - name: Copy the file to /home
      copy:
        src: /root/abhi
        dest: /home/abhi
        owner: root
        group: root
        mode: '0644'

