- name: test disable and enabled
  hosts: all
  tasks:
     - ansible.controller.host:
          controller_host:  http://10.74.250.184/
          inventory: source
          name: '10.74.254.253'
          state: absent
  
