- name: test disable and enabled
  hosts: all
  tasks:
     - ansible.controller.host:
          name: localhost
          validate_certs:  false
          controller_host:  http://10.74.250.184/
          controller_oauthtoken: dN1nZqGHtg8LFkvx00MAIvMueBfJgi
          controller_username: admin
          controller_password: redhat
          inventory: source
          enabled: false

  
