- name: show fact variable
  hosts: all
  tasks:
     - name: Print the fact variable value
       ansible.builtin.debug:
           msg: Hello
       environment:
         ANSIBLE_CALLBACK_WHITELIST: "json"
         ANSIBLE_STDOUT_CALLBACK: "json"
