- name: show fact variable
  hosts: all
  environment:
     ANSIBLE_CALLBACK_WHITELIST: "json"
     ANSIBLE_STDOUT_CALLBACK: "json"
  tasks:
     - name: Print the fact variable value
       ansible.builtin.debug:
           msg: Hello
       
