---
- name: ping module
  gather_facts: true
  hosts: all
  tasks:
    - name: Set variable for a machine
      ansible.builtin.set_fact:
        ServerMaintenance: MY_VARIABLE
        cacheable: yes

