- hosts: all
  tasks:
    - name: Create facts fqdn file
      file:
         path: /etc/ansible/facts.d
         state: directory
    - name: Create facts dir
      copy:
          dest: "/etc/ansible/facts.d/fqdn.fact"
          content: |
              [fqdn]
              fqdn=

