- name: Install and configure Apache
  hosts: all
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present
      tags: install

    - name: useradd
      ansible.builtin.user:
        name: abhi
      tags: start

    - name: Configure Apache
      template:
        src: /path/to/httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf
      tags: configure
